name: Run unit tests for ImaginaryNumbers class
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        python-version: [3.9]

    steps:
      - uses: actions/checkout@v3

      - name: Set up python
        uses: action/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
#          pip install -r ../requirements.txt

      - name: Run unittests
        run: python -m unittest ../imaginary_numbers_test.ImaginaryNumberTests